# Optimizer presets referenced by train_default.yaml:optimizer.name

adam:
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0
  amsgrad: false

sgdm:
  lr: 0.01
  momentum: 0.9
  nesterov: false
  weight_decay: 0.0

adagrad:
  lr: 0.01
  eps: 1.0e-10
  weight_decay: 0.0
