name: frl
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - scipy>=1.10
  - pandas>=2.0
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - tqdm>=4.66
  - pyyaml>=6.0
  - joblib>=1.3
  # PyTorch is platform-specific; install after activating the env:
  #   CPU   : pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
  #   CUDA12: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
