name: Docker images

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # GHCR push
    strategy:
      fail-fast: false
      matrix:
        flavor: [cpu, cuda]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image tags
        id: meta
        env:
          FLAVOR: ${{ matrix.flavor }}
        run: |
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LC}"
          SHA="${GITHUB_SHA::7}"
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            VER="${GITHUB_REF_NAME}"
            echo "tags=${IMAGE}:${FLAVOR}-latest,${IMAGE}:${FLAVOR}-${VER},${IMAGE}:${FLAVOR}-sha-${SHA}" >> "$GITHUB_OUTPUT"
          else
            echo "tags=${IMAGE}:${FLAVOR}-latest,${IMAGE}:${FLAVOR}-sha-${SHA}" >> "$GITHUB_OUTPUT"
          fi
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"

      - name: Build & Push (${{ matrix.flavor }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.flavor }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
